set_property SRC_FILE_INFO {cfile:C:/Users/vhall/Desktop/debug_prog/debug_prog.srcs/constrs_1/new/const.xdc rfile:../../../debug_prog.srcs/constrs_1/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports scl_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports sda_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_fpga_0] -min -add_delay 0.250 [get_ports sda_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock [get_clocks clk_fpga_0] -max -add_delay 0.350 [get_ports sda_0]
