set_property SRC_FILE_INFO {cfile:C:/Users/vhall/Desktop/output_test.srcs/constrs_1/new/const.xdc rfile:../../../output_test.srcs/constrs_1/new/const.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {out_val_0[1]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {out_val_0[0]}]
