set_property PACKAGE_PIN A13 [get_ports scl_0]
set_property PACKAGE_PIN A14 [get_ports sda_0]
set_property IOSTANDARD LVCMOS18 [get_ports scl_0]
set_property IOSTANDARD LVCMOS18 [get_ports sda_0]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
